name: Build for Linux & Windows

on:
  push:
    tags:
      - "v*"

jobs:
  build_and_release:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Installl packages
      run: cd student && npm install
    
    - name: Linux Build
      if: matrix.os == 'ubuntu-latest'
      run: cd student && npm run build
      
    - name: Windows build
      if: matrix.os == 'windows-latest'
      run: cd student && npm run build:win

    - name: Get filename
      id: get_filename
      run: |
        if [ "${{ runner.os }}" = "Linux" ]; then
          echo "::set-output name=filename::release/1.0.0/Next-Exam-Student_1.0.0.AppImage"
          echo "::set-output name=appName::Next-Exam-Student.AppImage"
        elif [ "${{ runner.os }}" = "Windows" ]; then
          echo "::set-output name=filename::release/1.0.0/Next-Exam-Student_1.0.0.exe"
          echo "::set-output name=appName::Next-Exam-Student.exe"
        fi
      shell: bash

    - name: Create Release
      if: github.run_number == 1
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Next-Exam-Student-${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./${{ steps.get_filename.outputs.filename }}
        asset_name: ${{ steps.get_filename.outputs.appName }}
        tag: ${{ github.ref }}
        overwrite: true
